version: '3'

services:
  teste-postgres-compose:
    image: postgres
    container_name: "postgres-db"
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "admin"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: "t@email.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "8081:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge